@startuml
hide circle

entity "Kisa" as kisa {
  *kisa_id : number
  --
  name : text
  description : text
}

entity "Kierros" as kierros {
  *kierros_id : number <<PK>>
  --
  kisa_id : number <<FK>>
}

entity "Tulos" as tulos {
  *tulos_id : number <<PK>>
  *pelaaja_id : number <<FK>>
  *rata_id : number <<FK>>
}

entity "Rata" as rata {
  *rata_id : number<<PK>>
  --
  name : text
}

entity "Pelaaja" as pelaaja {
  *pelaaja_id : number <<PK>>
  --
  name : text
}

kisa "0..*" -- "1..*" kierros
kierros "1" *-- "1..*" tulos
tulos "1" o-- "1" pelaaja
tulos "1" o-- "1" rata

@enduml