@startuml
hide circle

entity "Score" as score {
}

entity "Course" as course {
  name
}

entity "Player" as player {
  name
}

player  o--  score : achieved by
course  o--  score : achieved at

@enduml