version: '3'
services:
  flask:
    build: .
    environment:
     - FLASK_APP=frolftracker
     - FLASK_ENV= development
    ports:
     - "5000:5000"
    volumes:
     - .:/frolftracker
    command: flask run --host 0.0.0.0 
