MASON = "application/vnd.mason+json"
LINK_RELATIONS_URL = "/link-relations/"
PLAYER_PROFILE = "/profiles/player/"
COURSE_PROFILE = "/profiles/course/"
SCORE_PROFILE = "/profiles/score/"
ERROR_PROFILE = "/profiles/error/"
